services:
      piper-dimits-dash:
        container_name: piper-dimits-dash
        restart: unless-stopped
        tty: true
        volumes:
          - ./wav:/wav
          - ./models:/models
        # - ./config:json:/app/config.json # optional
        ports:
            - "8888:8888"
        build:
            dockerfile: ./.Dockerfile