services:
      piper-dimits-dash:
        container_name: piper-dimits-dash
        image: ghcr.io/mateuszmrw/piper-dimits-dash:latest
        restart: unless-stopped
        tty: true
        volumes:
          - ./wav:/wav
          - ./models:/models
        # - ./config:json:/app/config.json # optional
        environment:
        - TEXT_MAX_LENGTH=255 # Default value, can be overridden
        ports:
            - "8888:8888"